# Site settings
title: Cosas con alma
header-img: img/1.jpg
email: your-email@yourdomain.com
copyright_name: Cosas con alma
description: "***"
baseurl: ""
url: "http://cosasconalma.github.io"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia
email_username:  your-email@yourdomain.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
